{
 "title": "Test-Cluster-TiCDC",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "tidb_cluster",
    "label": "tidb_cluster",
    "query": "label_values(ticdc_processor_resolved_ts, tidb_cluster)"
   },
   {
    "name": "changefeed",
    "label": "Changefeed",
    "query": "label_values(ticdc_processor_resolved_ts{tidb_cluster=\"$tidb_cluster\"}, changefeed)"
   },
   {
    "name": "capture",
    "label": "TiCDC",
    "query": "label_values(ticdc_processor_resolved_ts{tidb_cluster=\"$tidb_cluster\"}, capture)"
   },
   {
    "name": "tikv_instance",
    "label": "TiKV",
    "query": "label_values(tikv_engine_size_bytes{tidb_cluster=\"$tidb_cluster\"}, instance)"
   },
   { "name": "spike_threshold", "label": "Latency spike (s) >", "query": "1, 3, 5, 10, 60, 300" }
  ]
 },
 "panels": [
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "description": "Uptime of TiCDC and TiKV",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "(time() - process_start_time_seconds{tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"})",
       "legendFormat": "TiCDC - {{instance}}"
      },
      {
       "expr": "(time() - process_start_time_seconds{tidb_cluster=\"$tidb_cluster\", job=\"tikv\"})",
       "legendFormat": "TiKV - {{instance}}"
      }
     ]
    },
    {
     "title": "Goroutine count",
     "type": "graph",
     "description": "Goroutine count of TiCDC",
     "gridPos": { "h": 7, "w": 6, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " go_goroutines{tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Open FD count",
     "type": "graph",
     "description": "The count of open FD count of TiCDC",
     "gridPos": { "h": 7, "w": 6, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Ownership",
     "type": "table",
     "description": "TiCDC cluster ownership status",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
     "targets": [
      {
       "expr": "rate(ticdc_owner_ownership_counter{tidb_cluster=\"$tidb_cluster\"}[30s])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "description": "CPU usage of TiCDC",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "description": "Memory usage of TiCDC",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"}",
       "legendFormat": "process-{{instance}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"}",
       "legendFormat": "heap-{{instance}}"
      }
     ]
    },
    {
     "title": "Ownership history",
     "type": "graph",
     "description": "The history of TiCDC cluster ownership, owner node has a value that is great than 0",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_owner_ownership_counter{tidb_cluster=\"$tidb_cluster\"}[30s])) by (instance) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Etcd health check duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(ticdc_server_etcd_health_check_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "p999-{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(ticdc_server_etcd_health_check_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "p99-{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(ticdc_server_etcd_health_check_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "p95-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Changefeed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Changefeed table count",
     "type": "table",
     "description": "The number of captured table of TiCDC nodes ",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(ticdc_processor_num_of_tables{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    },
    {
     "title": "Processor resolved ts",
     "type": "table",
     "description": "Internal resolved ts of TiCDC nodes",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 2 },
     "targets": [
      {
       "expr": "max(ticdc_processor_resolved_ts{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture,changefeed)",
       "legendFormat": "{{capture}}--{{changefeed}}"
      },
      {
       "expr": "max(ticdc_processor_checkpoint_ts{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture,changefeed) > 0",
       "legendFormat": "checkpoint-{{capture}}--{{changefeed}}"
      }
     ]
    },
    {
     "title": "Table resolved ts",
     "type": "table",
     "description": "Internal resolved ts of captured tables",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 2 },
     "targets": [
      {
       "expr": "max(ticdc_processor_table_resolved_ts{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture,changefeed,table)",
       "legendFormat": "{{capture}}-{{changefeed}}-{{table}}"
      },
      {
       "expr": "max(ticdc_processor_checkpoint_ts{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture,changefeed,table) > 0",
       "legendFormat": "checkpoint-{{changefeed}}"
      }
     ]
    },
    {
     "title": "Table count maintained by owner",
     "type": "table",
     "description": "The number of replicated tables maintained in owner",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(ticdc_owner_maintain_table_num{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\",type=\"total\"}) by (capture)",
       "legendFormat": "{{capture}}-total"
      },
      {
       "expr": "sum(ticdc_owner_maintain_table_num{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\",type=\"wip\"}) by (capture)",
       "legendFormat": "{{capture}}-wip"
      }
     ]
    },
    {
     "title": "Changefeed checkpoint",
     "type": "graph",
     "description": "The checkpoint ts of changefeeds.",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      {
       "expr": "max(ticdc_owner_checkpoint_ts{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}) by (changefeed) > 0",
       "legendFormat": "{{changefeed}}"
      },
      {
       "expr": "max(pd_cluster_tso{tidb_cluster=\"$tidb_cluster\"}) * 1000",
       "legendFormat": "approximate current time (s)"
      }
     ]
    },
    {
     "title": "PD etcd requests/s",
     "type": "graph",
     "description": "Request count of etcd operation per second",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_etcd_request_count{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (capture, type)",
       "legendFormat": "{{capture}}-{{type}}"
      }
     ]
    },
    {
     "title": "Exit error count/m",
     "type": "graph",
     "description": "The number of errors that interrupt changefeed per minute ",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(ticdc_processor_exit_with_error_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    },
    {
     "title": "Changefeed checkpoint lag",
     "type": "graph",
     "description": "The lag between changefeed checkpoint ts and the latest ts of upstream TiDB.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(ticdc_owner_checkpoint_ts_lag{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}) by (changefeed)",
       "legendFormat": "{{changefeed}}"
      }
     ]
    },
    {
     "title": "Processor resolved ts lag",
     "type": "graph",
     "description": "The lag between internal resolved ts and the latest ts of upstream TiDB.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(ticdc_processor_resolved_ts_lag{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture,changefeed)",
       "legendFormat": "{{capture}}--{{changefeed}}"
      }
     ]
    },
    {
     "title": "Sink write duration",
     "type": "heatmap",
     "description": "Sink write duration of changefeeds",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "max(rate(ticdc_sink_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sink write duration percentile",
     "type": "graph",
     "description": "Percentiles of sink write duration of changefeeds",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(ticdc_sink_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(ticdc_sink_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(ticdc_sink_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p999"
      }
     ]
    },
    {
     "title": "Sink write rows count/s",
     "type": "graph",
     "description": "The number of changed rows that are written to  downstream per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (rate(ticdc_sink_txn_batch_size_sum{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}"
      },
      {
       "expr": "sum (rate(ticdc_sink_txn_batch_size_sum{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (changefeed)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Sink write batch size percentile",
     "type": "graph",
     "description": "Percentiles of sink batch size",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ticdc_sink_txn_batch_size_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(ticdc_sink_txn_batch_size_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p99"
      }
     ]
    },
    {
     "title": "Flush sink duration",
     "type": "heatmap",
     "description": "Asynchronous flush sink duration of changefeeds",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "max(rate(ticdc_sink_flush_event_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Flush sink duration percentile",
     "type": "graph",
     "description": "Percentiles of asynchronous flush sink duration of changefeeds",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(ticdc_processor_flush_event_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (le,instance,type))",
       "legendFormat": "{{instance}}-{{type}}-p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(ticdc_sink_flush_event_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (le,instance,type))",
       "legendFormat": "{{instance}}-{{type}}-p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(ticdc_sink_flush_event_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (le,instance,type))",
       "legendFormat": "{{instance}}-{{type}}-p999"
      }
     ]
    },
    {
     "title": "MySQL sink conflict detect duration",
     "type": "heatmap",
     "description": "The duration of detecting and waiting conflict of MySQL sink",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "max(rate(ticdc_sink_conflict_detect_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "MySQL sink conflict detect duration percentile",
     "type": "graph",
     "description": "Percentiles of detecting and waiting conflict duration of MySQL sink",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95,sum(rate(ticdc_sink_conflict_detect_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p95"
      },
      {
       "expr": "histogram_quantile(0.99,sum(rate(ticdc_sink_conflict_detect_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p99"
      },
      {
       "expr": "histogram_quantile(0.999,sum(rate(ticdc_sink_conflict_detect_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p999"
      }
     ]
    },
    {
     "title": "MySQL sink worker load",
     "type": "graph",
     "description": "Distribution of MySQL worker loads",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(rate(ticdc_sink_bucket_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m]) <= 2)",
       "legendFormat": "0-2 row/s worker"
      },
      {
       "expr": "count(rate(ticdc_sink_bucket_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m]) > 2 and rate(ticdc_sink_bucket_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m]) <= 10)",
       "legendFormat": "2-10 row/s worker"
      },
      {
       "expr": "count(rate(ticdc_sink_bucket_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m]) > 10 and rate(ticdc_sink_bucket_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m]) <= 100)",
       "legendFormat": "10-100 row/s worker"
      },
      {
       "expr": "count(rate(ticdc_sink_bucket_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m]) > 100)",
       "legendFormat": ">100 row/s worker"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eventfeed count",
     "type": "graph",
     "description": "The number of established Eventfeed RPC between TiCDC and TiKV",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ticdc_kvclient_event_feed_count{tidb_cluster=\"$tidb_cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Event size percentile",
     "type": "graph",
     "description": "Percentiles of Eventfeed message size",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(ticdc_kvclient_event_size_bytes_bucket{tidb_cluster=\"$tidb_cluster\"}[1m])) by (le, instance))",
       "legendFormat": "{{instance}}-p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(ticdc_kvclient_event_size_bytes_bucket{tidb_cluster=\"$tidb_cluster\"}[1m])) by (le, instance))",
       "legendFormat": "{{instance}}-p95"
      }
     ]
    },
    {
     "title": "Eventfeed error/m",
     "type": "graph",
     "description": "The number of errors that interrupt Eventfeed RPC",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(ticdc_kvclient_event_feed_error_count{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "-sum(increase(pd_schedule_operators_count{tidb_cluster=\"$tidb_cluster\", event=\"create\", type=~\".*leader\"}[1m]))",
       "legendFormat": "transfer-leader"
      },
      {
       "expr": "-sum(increase(pd_schedule_operators_count{tidb_cluster=\"$tidb_cluster\", event=\"create\", type=~\".*(peer|region)\"}[1m]))",
       "legendFormat": "move-region"
      }
     ]
    },
    {
     "title": "KV client receive events/s",
     "type": "graph",
     "description": "The number of KV client received events from TiKV per seconds",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_kvclient_pull_event_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (instance, type)",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Puller output events/s",
     "type": "graph",
     "description": "The number of events that puller outputs to sorter \n per second",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (rate(ticdc_puller_txn_collect_event_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (instance, type)",
       "legendFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "Sink flush rows/s",
     "type": "graph",
     "description": "The number of rows that sink flushes to downstream per second",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_sink_total_flushed_rows_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    },
    {
     "title": "Puller buffer size",
     "type": "graph",
     "description": "The number of events that are buffered in Puller's memory buffer and output channel",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ticdc_puller_mem_buffer_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}} - output chan"
      },
      {
       "expr": "-sum(ticdc_puller_output_chan_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture) ",
       "legendFormat": "{{capture}} - memory  buffer"
      },
      {
       "expr": "-sum(ticdc_puller_event_chan_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}} - input chan"
      }
     ]
    },
    {
     "title": "Entry sorter buffer size",
     "type": "graph",
     "description": "The number of events that are buffered in Sorter's unsorted events buffer and output channel",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ticdc_puller_entry_sorter_unsorted_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}-unsorted events"
      },
      {
       "expr": "-sum(ticdc_puller_entry_sorter_output_chan_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}-ouput chan"
      }
     ]
    },
    {
     "title": "Sink/Mounter buffer size",
     "type": "graph",
     "description": "The number of events that are buffered in Processor's output channel and Mounter input channel",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ticdc_mounter_input_chan_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}-mounter input chan"
      },
      {
       "expr": "-sum(ticdc_sink_buffer_chan_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}-sink buffer chan"
      }
     ]
    },
    {
     "title": "Sink rows buffer size",
     "type": "graph",
     "description": "The number of rows(events) that are buffered in Sink's pending flush rows buffer",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ticdc_sink_total_rows_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture) - sum(ticdc_sink_total_flushed_rows_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    },
    {
     "title": "Entry sorter sort duration",
     "type": "heatmap",
     "description": "Duration of sorting unsorted events",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(rate(ticdc_puller_entry_sorter_sort_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Entry sorter sort duration percentile",
     "type": "graph",
     "description": "Percentiles of sorting events duration",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(ticdc_puller_entry_sorter_sort_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(ticdc_puller_entry_sorter_sort_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p95"
      }
     ]
    },
    {
     "title": "Entry sorter merge duration",
     "type": "heatmap",
     "description": "Duration of merging sorted events",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(rate(ticdc_puller_entry_sorter_merge_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Entry sorter merge duration percentile",
     "type": "graph",
     "description": "Percentiles of merging sorted events duration",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(ticdc_puller_entry_sorter_merge_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(ticdc_puller_entry_sorter_merge_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p95"
      }
     ]
    },
    {
     "title": "Mounter unmarshal duration",
     "type": "heatmap",
     "description": "Duration of unmarshal events from kv to SQL row",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "max(rate(ticdc_mounter_unmarshal_and_mount_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Mounter unmarshal duration percentile",
     "type": "graph",
     "description": "Percentiles of unmarshal events from kv to SQL row duration",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(ticdc_mounter_unmarshal_and_mount_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le, capture))",
       "legendFormat": "{{capture}}-p99"
      }
     ]
    },
    {
     "title": "KV client dispatch events/s",
     "type": "graph",
     "description": "The number of KV client dispatched event per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_kvclient_send_event_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (capture, changefeed, type)",
       "legendFormat": "{{capture}}-{{changefeed}}-{{type}}"
      },
      {
       "expr": "sum(rate(ticdc_kvclient_batch_resolved_event_size_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (capture, changefeed, table)",
       "legendFormat": "{{capture}}-{{changefeed}}-batch-resolved"
      }
     ]
    },
    {
     "title": "KV client batch resolved size",
     "type": "heatmap",
     "description": "The size of batch resolved ts message from TiKV",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(ticdc_kvclient_batch_resolved_event_size_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Unified Sorter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unified Sorter intake rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_sorter_consume_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (capture,changefeed)",
       "legendFormat": "{{capture}}-{{changefeed}}"
      }
     ]
    },
    {
     "title": "Unified Sorter event output rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_sorter_event_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (capture,changefeed)",
       "legendFormat": "{{capture}}-{{changefeed}}"
      }
     ]
    },
    {
     "title": "Unified Sorter on disk data size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ticdc_sorter_on_disk_data_size_gauge{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    },
    {
     "title": "Unified Sorter in-memory data size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ticdc_sorter_in_memory_data_size_gauge{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    },
    {
     "title": "Unified Sorter flush sizes",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(rate(ticdc_sorter_flush_count_histogram_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Unified Sorter merge size",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum(rate(ticdc_sorter_merge_count_histogram_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TiKV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CDC endpoint CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", name=~\"cdc_.*\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CDC worker CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", name=~\"cdcwkr.*\"}[1m])) by (instance)",
       "legendFormat": "{{instance}} - worker"
      },
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", name=~\"tso\"}[1m])) by (instance)",
       "legendFormat": "{{instance}} - tso"
      }
     ]
    },
    {
     "title": "gRPC message count",
     "type": "graph",
     "description": "The count of different kinds of gRPC message",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", type!=\"kv_gc\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "CDC memory",
     "type": "graph",
     "description": "The memory usage per TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(avg(process_resident_memory_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", job=~\"tikv.*\"}) by (instance)) - (avg(tikv_engine_block_cache_size_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", db=\"kv\"}) by(instance))",
       "legendFormat": "tikv-{{instance}}"
      },
      {
       "expr": "sum(tikv_cdc_sink_memory_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "sink-{{instance}}"
      },
      {
       "expr": "sum(tikv_cdc_old_value_cache_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "old-value-{{instance}}"
      },
      {
       "expr": "sum(tikv_cdc_sink_memory_capacity{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "sink-cap-{{instance}}"
      }
     ]
    },
    {
     "title": "Min resolved ts",
     "type": "graph",
     "description": "The minimal resolved ts of each TiKV",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      {
       "expr": "min(tikv_cdc_min_resolved_ts{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", job=~\"tikv.*\"}) by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "max(pd_cluster_tso{tidb_cluster=\"$tidb_cluster\"}) * 1000",
       "legendFormat": "Now"
      }
     ]
    },
    {
     "title": "Min resolved Region",
     "type": "graph",
     "description": "The minimal region ID of each TiKV",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tikv_cdc_min_resolved_ts_region{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Resolved ts lag duration 99.999% percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99999, sum(rate(tikv_cdc_resolved_ts_gap_seconds_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Initial scan duration",
     "type": "heatmap",
     "description": "The time consumed to CDC incremental scan",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_scan_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Initial scan duration percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, sum(rate(tikv_cdc_scan_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le, instance))",
       "legendFormat": "{{instance}}-p9999"
      }
     ]
    },
    {
     "title": "Initial scan tasks status",
     "type": "graph",
     "description": "The number of incremental scan task in different status.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_scan_tasks{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (type, instance)",
       "legendFormat": "{{instance}} - {{type}}"
      },
      {
       "expr": "sum(tikv_cdc_scan_tasks{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", type=\"total\"}) by (instance) - sum(tikv_cdc_scan_tasks{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", type=\"finish\"}) by (instance) - sum(tikv_cdc_scan_tasks{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", type=\"abort\"}) by (instance)",
       "legendFormat": "{{instance}} - ongoing"
      }
     ]
    },
    {
     "title": "Captured region count",
     "type": "graph",
     "description": "The memory usage per TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(tikv_cdc_captured_region_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "tikv-{{instance}}-total"
      },
      {
       "expr": "sum(tikv_cdc_region_resolve_status{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance, status)",
       "legendFormat": "tikv-{{instance}}-{{status}}"
      }
     ]
    },
    {
     "title": "CDC scan speed",
     "type": "graph",
     "description": "The speed of TiKV CDC incremental scan",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_scan_bytes_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", job=\"tikv\"}[30s])) by (instance)",
       "legendFormat": "tikv-{{instance}}"
      }
     ]
    },
    {
     "title": "CDC total scan bytes",
     "type": "graph",
     "description": "The total bytes of TiKV CDC incremental scan",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_scan_bytes_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", job=\"tikv\"}) by (instance)",
       "legendFormat": "tikv-{{instance}}"
      }
     ]
    },
    {
     "title": "Old value cache hit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(tikv_cdc_old_value_cache_access{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance) - sum(rate(tikv_cdc_old_value_cache_miss{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance)) / sum(rate(tikv_cdc_old_value_cache_access{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance)",
       "legendFormat": "hit-rate-{{instance}}"
      },
      {
       "expr": "-sum(rate(tikv_cdc_old_value_cache_miss{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance)",
       "legendFormat": "miss-{{instance}}"
      },
      {
       "expr": "-sum(rate(tikv_cdc_old_value_cache_miss_none{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance)",
       "legendFormat": "miss-none-{{instance}}"
      }
     ]
    },
    {
     "title": "Old value cache size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_old_value_cache_capacity{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "cap-{{instance}}"
      },
      {
       "expr": "sum(tikv_cdc_old_value_cache_length{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "len-{{instance}}"
      }
     ]
    },
    {
     "title": "Old value seek operation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_old_value_scan_details{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance, cf, tag)",
       "legendFormat": "{{instance}}-  {{cf}} - {{tag}}"
      }
     ]
    },
    {
     "title": "Old value seek duration",
     "type": "heatmap",
     "description": "The time consumed to get an old value (both from cache and from disk)",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_old_value_duration_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Old value seek duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 47 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_old_value_duration_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le, instance, tag))",
       "legendFormat": "{{instance}} - 99% - {{tag}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_old_value_duration_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le, instance, tag))",
       "legendFormat": "{{instance}} - 95% - {{tag}}"
      },
      {
       "expr": "sum(rate(tikv_cdc_old_value_duration_sum{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le, instance, tag) / sum(rate(tikv_cdc_old_value_duration_count{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le, instance, tag)",
       "legendFormat": "{{instance}} - avg - {{tag}}"
      }
     ]
    }
   ]
  }
 ]
}